require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/school_years", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SchoolYear. As you add validations to SchoolYear, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SchoolYear.create! valid_attributes
      get school_years_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      school_year = SchoolYear.create! valid_attributes
      get school_year_url(school_year)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_school_year_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      school_year = SchoolYear.create! valid_attributes
      get edit_school_year_url(school_year)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SchoolYear" do
        expect {
          post school_years_url, params: { school_year: valid_attributes }
        }.to change(SchoolYear, :count).by(1)
      end

      it "redirects to the created school_year" do
        post school_years_url, params: { school_year: valid_attributes }
        expect(response).to redirect_to(school_year_url(SchoolYear.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SchoolYear" do
        expect {
          post school_years_url, params: { school_year: invalid_attributes }
        }.to change(SchoolYear, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post school_years_url, params: { school_year: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested school_year" do
        school_year = SchoolYear.create! valid_attributes
        patch school_year_url(school_year), params: { school_year: new_attributes }
        school_year.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the school_year" do
        school_year = SchoolYear.create! valid_attributes
        patch school_year_url(school_year), params: { school_year: new_attributes }
        school_year.reload
        expect(response).to redirect_to(school_year_url(school_year))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        school_year = SchoolYear.create! valid_attributes
        patch school_year_url(school_year), params: { school_year: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested school_year" do
      school_year = SchoolYear.create! valid_attributes
      expect {
        delete school_year_url(school_year)
      }.to change(SchoolYear, :count).by(-1)
    end

    it "redirects to the school_years list" do
      school_year = SchoolYear.create! valid_attributes
      delete school_year_url(school_year)
      expect(response).to redirect_to(school_years_url)
    end
  end
end
