 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tenant_variables", type: :request do
  # TenantVariable. As you add validations to TenantVariable, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TenantVariable.create! valid_attributes
      get tenant_variables_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tenant_variable = TenantVariable.create! valid_attributes
      get tenant_variable_url(tenant_variable)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tenant_variable_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tenant_variable = TenantVariable.create! valid_attributes
      get edit_tenant_variable_url(tenant_variable)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TenantVariable" do
        expect {
          post tenant_variables_url, params: { tenant_variable: valid_attributes }
        }.to change(TenantVariable, :count).by(1)
      end

      it "redirects to the created tenant_variable" do
        post tenant_variables_url, params: { tenant_variable: valid_attributes }
        expect(response).to redirect_to(tenant_variable_url(TenantVariable.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TenantVariable" do
        expect {
          post tenant_variables_url, params: { tenant_variable: invalid_attributes }
        }.to change(TenantVariable, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tenant_variables_url, params: { tenant_variable: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tenant_variable" do
        tenant_variable = TenantVariable.create! valid_attributes
        patch tenant_variable_url(tenant_variable), params: { tenant_variable: new_attributes }
        tenant_variable.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tenant_variable" do
        tenant_variable = TenantVariable.create! valid_attributes
        patch tenant_variable_url(tenant_variable), params: { tenant_variable: new_attributes }
        tenant_variable.reload
        expect(response).to redirect_to(tenant_variable_url(tenant_variable))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tenant_variable = TenantVariable.create! valid_attributes
        patch tenant_variable_url(tenant_variable), params: { tenant_variable: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tenant_variable" do
      tenant_variable = TenantVariable.create! valid_attributes
      expect {
        delete tenant_variable_url(tenant_variable)
      }.to change(TenantVariable, :count).by(-1)
    end

    it "redirects to the tenant_variables list" do
      tenant_variable = TenantVariable.create! valid_attributes
      delete tenant_variable_url(tenant_variable)
      expect(response).to redirect_to(tenant_variables_url)
    end
  end
end
